
name: Manual Release

on:
    workflow_dispatch:
    inputs:
      py:
        required: true
        description: 'Python version to use for release'
        type: choice
        options:
          - '3.10'
          - '3.11'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Set up Python ${{ inputs.py }}
      uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.py }}"
    
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements/publish.txt

    - name: Configure git
      run: |
        git config --global user.name "semantic-release (via GitHub Actions)"
        git config --global user.email "semantic-release@gh"
    
    - name: semantic-release changelog
      run: semantic-release changelog

    - name: semantic-release publish if master
      if: github.ref == 'refs/heads/master'
      uses: relekang/python-semantic-release@master
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
